server:
  port: 8189
  servlet:
    context-path: /security

spring:
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: root






